language: node_js
node_js: 
  - "node"

dist: trusty
sudo: false

branches:
  only:
    - CI
    - master

addons:
  chrome: stable

script:
  ng test --watch=false --browsers=ChromeHeadless
  ng build